project                  = "cwb01-prod"
project_prefix           = "cwb01"
region                   = "us-east4"
environment              = "prod"
user_management_base_url = "https://api.cwb01.dsgov.nuvalence.io/um"
